### ISSUE TITLE
Move historical folders to different branches?

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/pandocs#325]
The `historical/` and `mediawiki-exporter/` folders are useful for their historical value, but are not relevant to operation of the "modern" docs, and are not updated anymore.
Should they be moved to a separate branch (`historical`, for example, or even one branch for each) instead, to de-clutter the root repository? We'd point out their existence in the readme on `master`.

**Comment by asiekierka** [comment]
I don't really like repositories which have branches for distinct content, myself. I would, however, group everything that is outdated to a separate folder - say, "old".

**Comment by ISSOtm** [comment]
I think a split would make sense here, as progression of the "main" docs is unrelated to those two folders (`historical/` is essentially frozen). It makes further sense so as to keep all modifications to `master` relevant to the "live" docs, esp. for scripting and CI.
Additionally, the setup described in the README does not concern those folders, either.

Since there are only two such folders, imo grouping them into a single folder wouldn't be worth the trouble.

**Comment by asiekierka** [comment]
An alternative option is to simply link to the last commit containing them, and remove them - unless we want to collect more historical documents?

**Comment by ISSOtm** [comment]
Pointing at a commit is the purpose of a branch or tag, though tags on GitHub are more associated with releases.

**Comment by avivace** [comment]
> The `historical/` and `mediawiki-exporter/` folders are useful for their historical value, but are not relevant to operation of the "modern" docs, and are not updated anymore.
> Should they be moved to a separate branch (`historical`, for example, or even one branch for each) instead, to de-clutter the root repository? We'd point out their existence in the readme on `master`.

Different branches for different content makes no sense, git-wise and accessibility wise.

I agree the mediawiki exporter can simply be moved on another repository. It is still relevant as it still fullfils it's scope, migrating from one technology to another.

An essential part of the "new" Pan Docs project is preservation of the research gbdev scene through the years. This is also why we engineered the mediawiki exporter to be able to keep every revision in git form. 

Also, following this rationale would mean removing everything non-source from the repository (why mdbook is here? why highlight.js is related to pan docs?). If you really feel like one folder clutters the development we can discuss about creating another repository (pandocs-historical) and move the folder there..

**Comment by ISSOtm** [comment]
> Also, following this rationale would mean removing everything non-source from the repository (why mdbook is here? why highlight.js is related to pan docs?). If you really feel like one folder clutters the development we can discuss about creating another repository (pandocs-historical) and move the folder there..

Okay, fair. The way I viewed it was that the repo should contain the current version of the docs and what's necessary to display them.

**Comment by avivace** [comment]
@ISSOtm Any update on this? What's your opinon on what I mentioned in my last comment?

**Comment by ISSOtm** [comment]
I put a thumbs up to signify my approval of it. I'm currently focusing on other PRs, so taking care of this is up for grabs.

**Comment by Rangi42** [comment]
I keep having to ignore the `historical/*` and `mediawiki-exporter/GbdevWiki-20200119114605.xml` content when grepping for things to read/fix. Was going to suggest deleting or moving them and found this issue.

ISSOtm suggested to move them both to a different repo or branch. avivace argued against branches, but said "I agree the mediawiki exporter can simply be moved on another repository", and ISSOtm "put a thumbs up to signify my approval of it."

However, this was then closed without moving either directory.

I'd like to either move `mediawiki-exporter` to its own repo (like how pret's [pokemon-reverse-engineering-tools](https://github.com/pret/pokemon-reverse-engineering-tools) and [gb-asm-tools](https://github.com/pret/gb-asm-tools) are separate fro their individual disasm projects), or at least move it inside the `historical` folder so that one whole thing can be ignored when working with pandocs.
