### ISSUE TITLE
Serial comma usage

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#360]
Decide if we should use it consistently, in some cases or never.

- https://en.wikipedia.org/wiki/Serial_comma
- https://academicguides.waldenu.edu/writingcenter/apa/other/serialcommas

**Comment by Rangi42** [comment]
For lists of long items, semicolons or a bulleted list may be even more clear.

**Comment by ISSOtm** [comment]
I prefer using it because of the reduced ambiguity when there are more than 2 items. Bullets are not always viable in running text, too.

**Comment by avivace** [comment]
Honestly, I fail to see the utility of enforcing the serial comma in a technical manual. In which cases it resolves ambiguity?

I think it's best omitted when not resolving ambiguity. Following "Public Works and Government Services Canada Translation Bureau's The Canadian Style: A Guide to Writing and Editing":

> In keeping with the general trend toward less punctuation, the final comma is best omitted where clarity permits, unless there is a need to emphasize the last element in a series.

**Comment by ISSOtm** [comment]
OK for me to follow that, then.

**Comment by aaaaaa123456789** [comment]
This is something so trivial that I'd say it hardly matters.
For lists of long items, the serial comma does help clarify: the Game Boy's addressable space consists of 40 KB allocated to the cartridge in two blocks, 16 KB allocated to working and video RAM, 15.5 KB of mirrored working RAM, 256 bytes of high RAM and I/O, and 256 bytes of OAM plus some leftover. (Of course, that could be a bulleted list, but sometimes it's simpler to just write such a list inline.)
For regular lists, it really doesn't matter. I personally don't use it unless it helps readability. But at the same time, adding pointless style rules increases the cost of contribution (in terms of mental load, if anything), so this begs the question: are these rules really necessary? Would anything of value be lost, style-wise or otherwise, if we just let contributors write the way they prefer?

**Comment by avivace** [comment]
> This is something so trivial that I'd say it hardly matters. For lists of long items, the serial comma does help clarify: the Game Boy's addressable space consists of 40 KB allocated to the cartridge in two blocks, 16 KB allocated to working and video RAM, 7.5 KB of mirrored working RAM, 256 bytes of high RAM and I/O, and 256 bytes of OAM plus some leftover. (Of course, that could be a bulleted list, but sometimes it's simpler to just write such a list inline.) For regular lists, it really doesn't matter. I personally don't use it unless it helps readability. But at the same time, adding pointless style rules increases the cost of contribution (in terms of mental load, if anything), so this begs the question: are these rules really necessary? Would anything of value be lost, style-wise or otherwise, if we just let contributors write the way they prefer?

Thanks for bringing that up - maybe we are overkilling it and it's not needed at all. I justed wanted some framework when reviewing, but if we start legislating this small things it's gonna be a burden to contribute.
