### ISSUE TITLE
Addresses for NR2x registers not mentioned in "Audio Registers"

### ISSUE THREAD

**Issue by jbshelton** [gbdev/pandocs#455]
Every other audio/hardware register has its corresponding address listed, and I'm surprised that the addresses for the NR2x registers were left out with the recent-ish overhaul of the audio section. I understand their function is left out due to it being identical to the NR1x registers, but their addresses in relation to the register names do not have the same scheme as the NR1x registers (NR10-NR14 = FF10-FF14, but NR21-NR24 = FF16-FF19, not FF21-FF24) and may be confusing to those new to the Gameboy's audio hardware. My memory isn't the best, so I frequently refer to the Pandocs when I want to use the hex address values instead of the name of the register. IMO the omission should be dealt with sooner rather than later.

**Comment by avivace** [comment]
Hey @jbshelton ! Thanks a lot for opening the issue. I edited it to remove the "IMO the omission should be dealt with sooner rather than later." phrase: our backlog is huge and I don't personally like making maintainers feel pushed to give more/less priority based on the "feeling" of users opening issues. Please refrain to do so in the future (unless we're speaking about security issues or other major causes). I'd also like to remind you that you can open a PR and start the work to "fix this omission" yourself.

**Comment by ISSOtm** [comment]
Well, the edit apparently didn't go through? Well, it was a small change so I made a PR myself. Still, thank you @avivace!
