### ISSUE TITLE
"Period changes take" in Audio_registers.md - NR13 paragraph

### ISSUE THREAD

**Issue by marcie1000** [gbdev/pandocs#491]
Hello,

It seams there is an unfinished sentence at the end of the paragraph NR13, it is only written "Period changes take".

**Comment by ISSOtm** [comment]
I think it's meant to say "Period changes take effect only when the previous period next expires"; cc @LIJI32 to confirm that that's right.

Also, not sure that formulation is super clear.

**Comment by LIJI32** [comment]
Yes, that's correct.

**Comment by ISSOtm** [comment]
Alright, now to find a way to phrase it that makes sense not just in retrospect.

**Comment by ISSOtm** [comment]
I wrote this in #334:

> Note that the value written to this field is not re-read by the hardware until a sweep iteration completes, or the channel is (re)triggered.

Does *that* sound clear? If so, then it can be used as a base for the new explanation.

**Comment by marcie1000** [comment]
> I think it's meant to say "Period changes take effect only when the previous period next expires"; cc @LIJI32 to confirm that that's right.
> 
> Also, not sure that formulation is super clear.



> I wrote this in #334:
> 
> > Note that the value written to this field is not re-read by the hardware until a sweep iteration completes, or the channel is (re)triggered.
> 
> Does _that_ sound clear? If so, then it can be used as a base for the new explanation.

To me, both sound pretty clear!

**Comment by ISSOtm** [comment]
I'm afraid of the first one only making sense "in retrospect", i.e. if you already understand what "when the period expires" means—it's really talking about the counter used to implement that period.

Regardless, it turns out that [the explanation was already added in #486](https://github.com/gbdev/pandocs/commit/3a23996e264550a8d13b2135bbbd278bf45cd1fb#diff-87ad7ba734041c686e8fce36377918555a9f19e7e0430f2a5a045e0528df5f6dR179), so maybe a warning-type box reading "writes to this register may not take effect immediately, see the next paragraph for more details" would do the trick?
